name: 'Build, Test CVE and Push Multi-Arch Image'
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: '${{ github.repository }}'
  DOCKERHUB_OWNER: jk11111
  CACHE_REPO: weather-app-cache
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: actions/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: actions/login-action@v3
        with:
          registry: '${{ env.GHCR_REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Log in to DockerHub
        uses: actions/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Extract metadata for GHCR
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: '${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}'
          tags: >
            type=sha,format=long

            type=ref,event=branch

            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' ||
            github.ref == 'refs/heads/master' }}
      - name: Build local image for CVE scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: 'local-image-test:latest'
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-image-test:latest'
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Build and push Multi-Arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
          cache-from: >-
            type=registry,ref=${{ env.DOCKERHUB_OWNER }}/${{ env.CACHE_REPO
            }}:cache
          cache-to: >-
            type=registry,ref=${{ env.DOCKERHUB_OWNER }}/${{ env.CACHE_REPO
            }}:cache,mode=max
